### ISSUE TITLE
> I like that you added new consumer tests; however, are you sure the test is running in our Django test workflow (I don't believe it is)?

### ISSUE THREAD

**Issue by amhajja** [uncc-hice/edukona_backend#54]
> I like that you added new consumer tests; however, are you sure the test is running in our Django test workflow (I don't believe it is)?
> 
> Also, please see the comments I left, and please resolve flake8 errors.

The tests for consumers aren't part of the django tests flow right now. But you can pull the code and run the following command to run the test: `pytest ./api/tests/consumer_tests.py`. In a future ticket we can integrate the consumer tests in the github workflow.

_Originally posted by @aaladaruncc in https://github.com/uncc-hice/edukona_backend/issues/46#issuecomment-2427409322_

**Comment by BruhLemma-Yadecha** [comment]
New WebSocket test workflow takes care of this.
